### ISSUE TITLE
MediaTypeExt does not exist

### ISSUE THREAD

**Issue by coreyauger** [paypal/squbs#358]
`bottles/bottlesvc/src/main/scala/org/squbs/bottlesvc/BottleSvc.scala:33: object MediaTypeExt is not a member of package org.squbs.unicomplex`

Does not appear in the repository from a search either.  Thanks.

**Comment by akara** [comment]
We need to refactor or remove those examples. They are a bit out of sync. Please start from the Activator templates (documented on README page) in the meantime instead.

**Comment by akara** [comment]
Forgot to mention. Since master is under development for 0.9 and Spray has been removed, that's where the `MediaTypeExt` got lost. You can work with the 0.8.X branch and have it all in place. This is likely to be removed for good and we have to re-work those examples.

**Comment by coreyauger** [comment]
Cool..  Was hoping to use akka http anyways.  Thanks for the update :)

**Comment by akara** [comment]
You can use Akka HTTP using the experimental mode with 0.8.1. Links to how to do so is on the home page. If you want the Flow API for serving http requests, it is available in 0.8.2-SNAPSHOT from the Sonatype snapshot repo, for instance: https://oss.sonatype.org/content/repositories/snapshots/org/squbs/squbs-unicomplex_2.11/

I would not use 0.9.0-SNAPSHOT for another week. We're still doing some major refactoring. We're at the last stages of moving things around. After that all the additions are minor.

**Comment by coreyauger** [comment]
Ok that is very helpful thanks :)  I have been following your work which originated for me with this talk..
https://www.youtube.com/watch?v=15jAG6-T_KE

The plans I have for refactoring my platform a very tied to the usage of kafka and streams.  A few question for you.

Will streams complement or replace your current Orchestration DSL.
Is there a simple scaffold setup for Squbs that creates a service that integrates with akka/reactive-kafka or what in your mind would be setup steps for this?

I know you are busy so I very much appreciate any time you can give me here :)

**Comment by akara** [comment]
Thanks for following! If you don't mind, can we post the questions beyond this issue on https://gitter.im/paypal/squbs ? It allows others who are not watching the issue to chime in and answers many generic questions. Thanks!

**Comment by anilgursel** [comment]
Issue no longer valid in Akka HTTP with squbs 0.9.0.
